/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapPanel.java
 *
 * Created on 2/08/2010, 10:54:22 AM
 */
package gui;

/**
 *
 * @author geoma48p
 */
public class MapPanel303 extends javax.swing.JPanel implements IMapPanel {

    ButtonProcessor processor = new ButtonProcessor();

    /** Creates new form MapPanel */
    public MapPanel303() {
        initComponents();
        processor.processButtons(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jButton2 = new javax.swing.JLabel();
      jButton3 = new javax.swing.JLabel();
      jButton7 = new javax.swing.JLabel();
      jButton12 = new javax.swing.JLabel();
      jButton4 = new javax.swing.JLabel();
      jButton5 = new javax.swing.JLabel();
      jButton6 = new javax.swing.JLabel();
      jButton8 = new javax.swing.JLabel();
      jButton9 = new javax.swing.JLabel();
      jButton10 = new javax.swing.JLabel();
      jButton11 = new javax.swing.JLabel();
      jButton13 = new javax.swing.JLabel();
      jButton14 = new javax.swing.JLabel();
      jButton15 = new javax.swing.JLabel();
      jButton16 = new javax.swing.JLabel();
      jButton32 = new javax.swing.JLabel();
      jButton33 = new javax.swing.JLabel();
      jButton34 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jButton17 = new javax.swing.JLabel();
      jButton18 = new javax.swing.JLabel();
      jButton19 = new javax.swing.JLabel();
      jButton20 = new javax.swing.JLabel();
      jButton21 = new javax.swing.JLabel();
      jButton22 = new javax.swing.JLabel();
      jButton23 = new javax.swing.JLabel();
      jButton24 = new javax.swing.JLabel();
      jButton25 = new javax.swing.JLabel();
      jButton26 = new javax.swing.JLabel();
      jButton27 = new javax.swing.JLabel();
      jButton28 = new javax.swing.JLabel();
      jButton29 = new javax.swing.JLabel();
      jButton30 = new javax.swing.JLabel();
      jButton31 = new javax.swing.JLabel();
      lblQueue = new javax.swing.JLabel();
      lblTopSpacer = new javax.swing.JLabel();
      lblBottomSpacer = new javax.swing.JLabel();

      jPanel1.setName("jPanel1"); // NOI18N
      jPanel1.setLayout(new java.awt.GridLayout(6, 3, 5, 5));

      jButton2.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton2.setText("01");
      jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton2.setName("jButton2"); // NOI18N
      jPanel1.add(jButton2);

      jButton3.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton3.setText("02");
      jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton3.setName("jButton3"); // NOI18N
      jPanel1.add(jButton3);

      jButton7.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton7.setText("03");
      jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton7.setName("jButton7"); // NOI18N
      jPanel1.add(jButton7);

      jButton12.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton12.setText("07");
      jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton12.setName("jButton12"); // NOI18N
      jPanel1.add(jButton12);

      jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
      jButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton4.setText("08");
      jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton4.setName("jButton4"); // NOI18N
      jPanel1.add(jButton4);

      jButton5.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton5.setText("09");
      jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton5.setName("jButton5"); // NOI18N
      jPanel1.add(jButton5);

      jButton6.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton6.setText("13");
      jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton6.setName("jButton6"); // NOI18N
      jPanel1.add(jButton6);

      jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
      jButton8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton8.setText("14");
      jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton8.setName("jButton8"); // NOI18N
      jPanel1.add(jButton8);

      jButton9.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton9.setText("15");
      jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton9.setName("jButton9"); // NOI18N
      jPanel1.add(jButton9);

      jButton10.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton10.setText("19");
      jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton10.setName("jButton10"); // NOI18N
      jPanel1.add(jButton10);

      jButton11.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton11.setText("20");
      jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton11.setName("jButton11"); // NOI18N
      jPanel1.add(jButton11);

      jButton13.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton13.setText("21");
      jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton13.setName("jButton13"); // NOI18N
      jPanel1.add(jButton13);

      jButton14.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton14.setText("25");
      jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton14.setName("jButton14"); // NOI18N
      jPanel1.add(jButton14);

      jButton15.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton15.setText("26");
      jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton15.setName("jButton15"); // NOI18N
      jPanel1.add(jButton15);

      jButton16.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton16.setText("27");
      jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton16.setName("jButton16"); // NOI18N
      jPanel1.add(jButton16);

      jButton32.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton32.setText("31");
      jButton32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton32.setName("jButton32"); // NOI18N
      jPanel1.add(jButton32);

      jButton33.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton33.setText("32");
      jButton33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton33.setName("jButton33"); // NOI18N
      jPanel1.add(jButton33);

      jButton34.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton34.setText("33");
      jButton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton34.setName("jButton34"); // NOI18N
      jPanel1.add(jButton34);

      jPanel2.setName("jPanel2"); // NOI18N
      jPanel2.setLayout(new java.awt.GridLayout(5, 3, 5, 5));

      jButton17.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton17.setText("04");
      jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton17.setName("jButton17"); // NOI18N
      jPanel2.add(jButton17);

      jButton18.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton18.setText("05");
      jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton18.setName("jButton18"); // NOI18N
      jPanel2.add(jButton18);

      jButton19.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton19.setText("06");
      jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton19.setName("jButton19"); // NOI18N
      jPanel2.add(jButton19);

      jButton20.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton20.setText("10");
      jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton20.setName("jButton20"); // NOI18N
      jPanel2.add(jButton20);

      jButton21.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton21.setText("11");
      jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton21.setName("jButton21"); // NOI18N
      jPanel2.add(jButton21);

      jButton22.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton22.setText("12");
      jButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton22.setName("jButton22"); // NOI18N
      jPanel2.add(jButton22);

      jButton23.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton23.setText("16");
      jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton23.setName("jButton23"); // NOI18N
      jPanel2.add(jButton23);

      jButton24.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton24.setText("17");
      jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton24.setName("jButton24"); // NOI18N
      jPanel2.add(jButton24);

      jButton25.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton25.setText("18");
      jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton25.setName("jButton25"); // NOI18N
      jPanel2.add(jButton25);

      jButton26.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton26.setText("22");
      jButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton26.setName("jButton26"); // NOI18N
      jPanel2.add(jButton26);

      jButton27.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton27.setText("23");
      jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton27.setName("jButton27"); // NOI18N
      jPanel2.add(jButton27);

      jButton28.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton28.setText("24");
      jButton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton28.setName("jButton28"); // NOI18N
      jPanel2.add(jButton28);

      jButton29.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton29.setText("28");
      jButton29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton29.setName("jButton29"); // NOI18N
      jPanel2.add(jButton29);

      jButton30.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton30.setText("29");
      jButton30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton30.setName("jButton30"); // NOI18N
      jPanel2.add(jButton30);

      jButton31.setFont(new java.awt.Font("Tahoma", 1, 36));
      jButton31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jButton31.setText("30");
      jButton31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jButton31.setName("jButton31"); // NOI18N
      jPanel2.add(jButton31);

      lblQueue.setFont(new java.awt.Font("Tahoma", 1, 48));
      lblQueue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblQueue.setName("lblQueue"); // NOI18N

      lblTopSpacer.setFont(new java.awt.Font("Dialog", 1, 3));
      lblTopSpacer.setText(" ");
      lblTopSpacer.setName("lblTopSpacer"); // NOI18N

      lblBottomSpacer.setFont(new java.awt.Font("Dialog", 1, 8));
      lblBottomSpacer.setText(" ");
      lblBottomSpacer.setName("lblBottomSpacer"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lblQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                  .addGap(28, 28, 28)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblBottomSpacer)
                     .addComponent(lblTopSpacer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(lblTopSpacer, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(lblBottomSpacer))
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jButton10;
   private javax.swing.JLabel jButton11;
   private javax.swing.JLabel jButton12;
   private javax.swing.JLabel jButton13;
   private javax.swing.JLabel jButton14;
   private javax.swing.JLabel jButton15;
   private javax.swing.JLabel jButton16;
   private javax.swing.JLabel jButton17;
   private javax.swing.JLabel jButton18;
   private javax.swing.JLabel jButton19;
   private javax.swing.JLabel jButton2;
   private javax.swing.JLabel jButton20;
   private javax.swing.JLabel jButton21;
   private javax.swing.JLabel jButton22;
   private javax.swing.JLabel jButton23;
   private javax.swing.JLabel jButton24;
   private javax.swing.JLabel jButton25;
   private javax.swing.JLabel jButton26;
   private javax.swing.JLabel jButton27;
   private javax.swing.JLabel jButton28;
   private javax.swing.JLabel jButton29;
   private javax.swing.JLabel jButton3;
   private javax.swing.JLabel jButton30;
   private javax.swing.JLabel jButton31;
   private javax.swing.JLabel jButton32;
   private javax.swing.JLabel jButton33;
   private javax.swing.JLabel jButton34;
   private javax.swing.JLabel jButton4;
   private javax.swing.JLabel jButton5;
   private javax.swing.JLabel jButton6;
   private javax.swing.JLabel jButton7;
   private javax.swing.JLabel jButton8;
   private javax.swing.JLabel jButton9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JLabel lblBottomSpacer;
   private javax.swing.JLabel lblQueue;
   private javax.swing.JLabel lblTopSpacer;
   // End of variables declaration//GEN-END:variables

    public void requestHelp(final int id) {
        processor.request(id);
    }

    public void cancelRequest(int id) {
        processor.cancel(id);
    }
}
