/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapPanel.java
 *
 * Created on 2/08/2010, 10:54:22 AM
 */
package gui;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author geoma48p
 */
public class MapPanel316 extends javax.swing.JPanel implements IMapPanel {

   /** Creates new form MapPanel */
   public MapPanel316() {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSpacer = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        lblQueue = new javax.swing.JLabel();

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(5, 7, 5, 5));

        lblSpacer.setName("lblSpacer"); // NOI18N
        jPanel1.add(lblSpacer);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton2.setText("01");
        jButton2.setName("jButton2"); // NOI18N
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton3.setText("02");
        jButton3.setName("jButton3"); // NOI18N
        jPanel1.add(jButton3);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton7.setText("03");
        jButton7.setName("jButton7"); // NOI18N
        jPanel1.add(jButton7);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton17.setText("04");
        jButton17.setName("jButton17"); // NOI18N
        jPanel1.add(jButton17);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton18.setText("05");
        jButton18.setName("jButton18"); // NOI18N
        jPanel1.add(jButton18);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton19.setText("06");
        jButton19.setName("jButton19"); // NOI18N
        jPanel1.add(jButton19);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton12.setText("07");
        jButton12.setName("jButton12"); // NOI18N
        jPanel1.add(jButton12);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton4.setText("08");
        jButton4.setName("jButton4"); // NOI18N
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton5.setText("09");
        jButton5.setName("jButton5"); // NOI18N
        jPanel1.add(jButton5);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton20.setText("10");
        jButton20.setName("jButton20"); // NOI18N
        jPanel1.add(jButton20);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton21.setText("11");
        jButton21.setName("jButton21"); // NOI18N
        jPanel1.add(jButton21);

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton22.setText("12");
        jButton22.setName("jButton22"); // NOI18N
        jPanel1.add(jButton22);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton6.setText("13");
        jButton6.setName("jButton6"); // NOI18N
        jPanel1.add(jButton6);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton8.setText("14");
        jButton8.setName("jButton8"); // NOI18N
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton9.setText("15");
        jButton9.setName("jButton9"); // NOI18N
        jPanel1.add(jButton9);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton23.setText("16");
        jButton23.setName("jButton23"); // NOI18N
        jPanel1.add(jButton23);

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton24.setText("17");
        jButton24.setName("jButton24"); // NOI18N
        jPanel1.add(jButton24);

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton25.setText("18");
        jButton25.setName("jButton25"); // NOI18N
        jPanel1.add(jButton25);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton10.setText("19");
        jButton10.setName("jButton10"); // NOI18N
        jPanel1.add(jButton10);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton11.setText("20");
        jButton11.setName("jButton11"); // NOI18N
        jPanel1.add(jButton11);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton13.setText("21");
        jButton13.setName("jButton13"); // NOI18N
        jPanel1.add(jButton13);

        jButton26.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton26.setText("22");
        jButton26.setName("jButton26"); // NOI18N
        jPanel1.add(jButton26);

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton27.setText("23");
        jButton27.setName("jButton27"); // NOI18N
        jPanel1.add(jButton27);

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton28.setText("24");
        jButton28.setName("jButton28"); // NOI18N
        jPanel1.add(jButton28);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton14.setText("25");
        jButton14.setName("jButton14"); // NOI18N
        jPanel1.add(jButton14);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton15.setText("26");
        jButton15.setName("jButton15"); // NOI18N
        jPanel1.add(jButton15);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton16.setText("27");
        jButton16.setName("jButton16"); // NOI18N
        jPanel1.add(jButton16);

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton29.setText("28");
        jButton29.setName("jButton29"); // NOI18N
        jPanel1.add(jButton29);

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton30.setText("29");
        jButton30.setName("jButton30"); // NOI18N
        jPanel1.add(jButton30);

        jButton31.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton31.setText("30");
        jButton31.setName("jButton31"); // NOI18N
        jPanel1.add(jButton31);

        jButton32.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton32.setText("31");
        jButton32.setName("jButton32"); // NOI18N
        jPanel1.add(jButton32);

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton33.setText("32");
        jButton33.setName("jButton33"); // NOI18N
        jPanel1.add(jButton33);

        jButton34.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton34.setText("33");
        jButton34.setName("jButton34"); // NOI18N
        jPanel1.add(jButton34);

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 36));
        jButton37.setText("34");
        jButton37.setName("jButton37"); // NOI18N
        jPanel1.add(jButton37);

        lblQueue.setFont(new java.awt.Font("Tahoma", 1, 48));
        lblQueue.setName("lblQueue"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQueue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQueue;
    private javax.swing.JLabel lblSpacer;
    // End of variables declaration//GEN-END:variables


   public JLabel getQueueLabel() {
      throw new UnsupportedOperationException("Not supported yet.");
   }

   public JPanel getPanel() {
      throw new UnsupportedOperationException("Not supported yet.");
   }

   public LabelProcessor getProcessor() {
      throw new UnsupportedOperationException("Not supported yet.");
   }
}
