package gui;

import javax.swing.JLabel;

/**
 *
 * @author Mark
 */
public class QueuePanel extends javax.swing.JPanel {

   /** Creates new form QueuePanel */
   public QueuePanel() {
      super();
      initComponents();
   }

   public static JLabel getQueueLabel() {
      return LBLQUEUE;
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
      scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
      scrollPane.setName("scrollPane"); // NOI18N

      LBLQUEUE.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
      LBLQUEUE.setName("LBLQUEUE"); // NOI18N
      scrollPane.setViewportView(LBLQUEUE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private static final javax.swing.JLabel LBLQUEUE = new javax.swing.JLabel();
   private final javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
   // End of variables declaration//GEN-END:variables
}
