package gui.maps;

import javax.swing.JPanel;

/**
 *
 * @author Gary Burrows, and Mark
 */
public class MapPanelRabel extends JPanel {

   /** Creates new form MapPanel */
   public MapPanelRabel() {
      super();
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      contentPanel = new javax.swing.JPanel();
      leftPanel = new javax.swing.JPanel();
      lblMachine45 = new javax.swing.JLabel();
      lblMachine43 = new javax.swing.JLabel();
      lblMachine44 = new javax.swing.JLabel();
      lblMachine49 = new javax.swing.JLabel();
      lblMachine48 = new javax.swing.JLabel();
      lblMachine47 = new javax.swing.JLabel();
      lblMachine46 = new javax.swing.JLabel();
      lblMachine42 = new javax.swing.JLabel();
      lblMachine41 = new javax.swing.JLabel();
      lblMachine40 = new javax.swing.JLabel();
      lblMachine38 = new javax.swing.JLabel();
      lblMachine39 = new javax.swing.JLabel();
      middlePanel = new javax.swing.JPanel();
      lblMachine61 = new javax.swing.JLabel();
      lblMachine60 = new javax.swing.JLabel();
      lblMachine59 = new javax.swing.JLabel();
      lblMachine54 = new javax.swing.JLabel();
      lblMachine58 = new javax.swing.JLabel();
      lblMachine57 = new javax.swing.JLabel();
      lblMachine56 = new javax.swing.JLabel();
      lblMachine55 = new javax.swing.JLabel();
      lblMachine52 = new javax.swing.JLabel();
      lblMachine53 = new javax.swing.JLabel();
      lblMachine50 = new javax.swing.JLabel();
      lblMachine51 = new javax.swing.JLabel();
      rightPanel = new javax.swing.JPanel();
      lblMachine64 = new javax.swing.JLabel();
      lblMachine73 = new javax.swing.JLabel();
      lblMachine71 = new javax.swing.JLabel();
      lblMachine69 = new javax.swing.JLabel();
      lblMachine68 = new javax.swing.JLabel();
      lblMachine67 = new javax.swing.JLabel();
      lblMachine66 = new javax.swing.JLabel();
      lblMachine65 = new javax.swing.JLabel();
      lblMachine63 = new javax.swing.JLabel();
      lblMachine62 = new javax.swing.JLabel();
      lblMachine70 = new javax.swing.JLabel();
      lblMachine72 = new javax.swing.JLabel();

      contentPanel.setName("contentPanel"); // NOI18N
      contentPanel.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

      leftPanel.setName("leftPanel"); // NOI18N
      leftPanel.setLayout(new java.awt.GridLayout(3, 4, 5, 5));

      lblMachine45.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine45.setText("2");
      lblMachine45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine45.setName("lblMachine45"); // NOI18N
      leftPanel.add(lblMachine45);

      lblMachine43.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine43.setText("3");
      lblMachine43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine43.setName("lblMachine43"); // NOI18N
      leftPanel.add(lblMachine43);

      lblMachine44.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine44.setText("4");
      lblMachine44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine44.setName("lblMachine44"); // NOI18N
      leftPanel.add(lblMachine44);

      lblMachine49.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine49.setText("5");
      lblMachine49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine49.setName("lblMachine49"); // NOI18N
      leftPanel.add(lblMachine49);

      lblMachine48.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine48.setText("14");
      lblMachine48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine48.setName("lblMachine48"); // NOI18N
      leftPanel.add(lblMachine48);

      lblMachine47.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine47.setText("15");
      lblMachine47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine47.setName("lblMachine47"); // NOI18N
      leftPanel.add(lblMachine47);

      lblMachine46.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine46.setText("16");
      lblMachine46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine46.setName("lblMachine46"); // NOI18N
      leftPanel.add(lblMachine46);

      lblMachine42.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine42.setText("17");
      lblMachine42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine42.setName("lblMachine42"); // NOI18N
      leftPanel.add(lblMachine42);

      lblMachine41.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine41.setText("26");
      lblMachine41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine41.setName("lblMachine41"); // NOI18N
      leftPanel.add(lblMachine41);

      lblMachine40.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine40.setText("27");
      lblMachine40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine40.setName("lblMachine40"); // NOI18N
      leftPanel.add(lblMachine40);

      lblMachine38.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine38.setText("28");
      lblMachine38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine38.setName("lblMachine38"); // NOI18N
      leftPanel.add(lblMachine38);

      lblMachine39.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine39.setText("29");
      lblMachine39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine39.setName("lblMachine39"); // NOI18N
      leftPanel.add(lblMachine39);

      contentPanel.add(leftPanel);

      middlePanel.setName("middlePanel"); // NOI18N
      middlePanel.setLayout(new java.awt.GridLayout(3, 4, 5, 5));

      lblMachine61.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine61.setText("6");
      lblMachine61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine61.setName("lblMachine61"); // NOI18N
      middlePanel.add(lblMachine61);

      lblMachine60.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine60.setText("7");
      lblMachine60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine60.setName("lblMachine60"); // NOI18N
      middlePanel.add(lblMachine60);

      lblMachine59.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine59.setText("8");
      lblMachine59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine59.setName("lblMachine59"); // NOI18N
      middlePanel.add(lblMachine59);

      lblMachine54.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine54.setText("9");
      lblMachine54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine54.setName("lblMachine54"); // NOI18N
      middlePanel.add(lblMachine54);

      lblMachine58.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine58.setText("18");
      lblMachine58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine58.setName("lblMachine58"); // NOI18N
      middlePanel.add(lblMachine58);

      lblMachine57.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine57.setText("19");
      lblMachine57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine57.setName("lblMachine57"); // NOI18N
      middlePanel.add(lblMachine57);

      lblMachine56.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine56.setText("20");
      lblMachine56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine56.setName("lblMachine56"); // NOI18N
      middlePanel.add(lblMachine56);

      lblMachine55.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine55.setText("21");
      lblMachine55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine55.setName("lblMachine55"); // NOI18N
      middlePanel.add(lblMachine55);

      lblMachine52.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine52.setText("30");
      lblMachine52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine52.setName("lblMachine52"); // NOI18N
      middlePanel.add(lblMachine52);

      lblMachine53.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine53.setText("31");
      lblMachine53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine53.setName("lblMachine53"); // NOI18N
      middlePanel.add(lblMachine53);

      lblMachine50.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine50.setText("32");
      lblMachine50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine50.setName("lblMachine50"); // NOI18N
      middlePanel.add(lblMachine50);

      lblMachine51.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine51.setText("33");
      lblMachine51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine51.setName("lblMachine51"); // NOI18N
      middlePanel.add(lblMachine51);

      contentPanel.add(middlePanel);

      rightPanel.setName("rightPanel"); // NOI18N
      rightPanel.setLayout(new java.awt.GridLayout(3, 4, 5, 5));

      lblMachine64.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine64.setText("10");
      lblMachine64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine64.setName("lblMachine64"); // NOI18N
      rightPanel.add(lblMachine64);

      lblMachine73.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine73.setText("11");
      lblMachine73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine73.setName("lblMachine73"); // NOI18N
      rightPanel.add(lblMachine73);

      lblMachine71.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine71.setText("12");
      lblMachine71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine71.setName("lblMachine71"); // NOI18N
      rightPanel.add(lblMachine71);

      lblMachine69.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine69.setText("13");
      lblMachine69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine69.setName("lblMachine69"); // NOI18N
      rightPanel.add(lblMachine69);

      lblMachine68.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine68.setText("22");
      lblMachine68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine68.setName("lblMachine68"); // NOI18N
      rightPanel.add(lblMachine68);

      lblMachine67.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine67.setText("23");
      lblMachine67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine67.setName("lblMachine67"); // NOI18N
      rightPanel.add(lblMachine67);

      lblMachine66.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine66.setText("24");
      lblMachine66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine66.setName("lblMachine66"); // NOI18N
      rightPanel.add(lblMachine66);

      lblMachine65.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine65.setText("25");
      lblMachine65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine65.setName("lblMachine65"); // NOI18N
      rightPanel.add(lblMachine65);

      lblMachine63.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine63.setText("34");
      lblMachine63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine63.setName("lblMachine63"); // NOI18N
      rightPanel.add(lblMachine63);

      lblMachine62.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine62.setText("35");
      lblMachine62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine62.setName("lblMachine62"); // NOI18N
      rightPanel.add(lblMachine62);

      lblMachine70.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine70.setText("36");
      lblMachine70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine70.setName("lblMachine70"); // NOI18N
      rightPanel.add(lblMachine70);

      lblMachine72.setFont(new java.awt.Font("Tahoma", 1, 40));
      lblMachine72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine72.setText("37");
      lblMachine72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      lblMachine72.setName("lblMachine72"); // NOI18N
      rightPanel.add(lblMachine72);

      contentPanel.add(rightPanel);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel contentPanel;
   private javax.swing.JLabel lblMachine38;
   private javax.swing.JLabel lblMachine39;
   private javax.swing.JLabel lblMachine40;
   private javax.swing.JLabel lblMachine41;
   private javax.swing.JLabel lblMachine42;
   private javax.swing.JLabel lblMachine43;
   private javax.swing.JLabel lblMachine44;
   private javax.swing.JLabel lblMachine45;
   private javax.swing.JLabel lblMachine46;
   private javax.swing.JLabel lblMachine47;
   private javax.swing.JLabel lblMachine48;
   private javax.swing.JLabel lblMachine49;
   private javax.swing.JLabel lblMachine50;
   private javax.swing.JLabel lblMachine51;
   private javax.swing.JLabel lblMachine52;
   private javax.swing.JLabel lblMachine53;
   private javax.swing.JLabel lblMachine54;
   private javax.swing.JLabel lblMachine55;
   private javax.swing.JLabel lblMachine56;
   private javax.swing.JLabel lblMachine57;
   private javax.swing.JLabel lblMachine58;
   private javax.swing.JLabel lblMachine59;
   private javax.swing.JLabel lblMachine60;
   private javax.swing.JLabel lblMachine61;
   private javax.swing.JLabel lblMachine62;
   private javax.swing.JLabel lblMachine63;
   private javax.swing.JLabel lblMachine64;
   private javax.swing.JLabel lblMachine65;
   private javax.swing.JLabel lblMachine66;
   private javax.swing.JLabel lblMachine67;
   private javax.swing.JLabel lblMachine68;
   private javax.swing.JLabel lblMachine69;
   private javax.swing.JLabel lblMachine70;
   private javax.swing.JLabel lblMachine71;
   private javax.swing.JLabel lblMachine72;
   private javax.swing.JLabel lblMachine73;
   private javax.swing.JPanel leftPanel;
   private javax.swing.JPanel middlePanel;
   private javax.swing.JPanel rightPanel;
   // End of variables declaration//GEN-END:variables
}
