/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.maps;

/**
 *
 * @author mark
 */
public class MapPanel318 extends javax.swing.JPanel {

   /**
    * Creates new form MapPanel318
    */
   public MapPanel318() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      leftPanel = new javax.swing.JPanel();
      lblMachine2 = new javax.swing.JLabel();
      lblMachine3 = new javax.swing.JLabel();
      lblMachine7 = new javax.swing.JLabel();
      lblMachine12 = new javax.swing.JLabel();
      lblMachine4 = new javax.swing.JLabel();
      lblMachine5 = new javax.swing.JLabel();
      lblMachine6 = new javax.swing.JLabel();
      lblMachine8 = new javax.swing.JLabel();
      lblMachine9 = new javax.swing.JLabel();
      rightPanel = new javax.swing.JPanel();
      lblMachine18 = new javax.swing.JLabel();
      lblMachine21 = new javax.swing.JLabel();
      lblMachine22 = new javax.swing.JLabel();
      lblMachine23 = new javax.swing.JLabel();
      lblMachine24 = new javax.swing.JLabel();
      lblMachine25 = new javax.swing.JLabel();
      lblMachine26 = new javax.swing.JLabel();
      lblMachine27 = new javax.swing.JLabel();
      lblMachine28 = new javax.swing.JLabel();
      lblMachine29 = new javax.swing.JLabel();
      lblMachine30 = new javax.swing.JLabel();
      lblMachine31 = new javax.swing.JLabel();

      leftPanel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

      lblMachine2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine2.setText("6");
      lblMachine2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine2);

      lblMachine3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine3.setText("5");
      lblMachine3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine3);

      lblMachine7.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine7.setText("4");
      lblMachine7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine7);

      lblMachine12.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine12.setText("13");
      lblMachine12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine12);

      lblMachine4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine4.setText("12");
      lblMachine4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine4);

      lblMachine5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine5.setText("11");
      lblMachine5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine5);

      lblMachine6.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine6.setText("20");
      lblMachine6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine6);

      lblMachine8.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine8.setText("19");
      lblMachine8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine8);

      lblMachine9.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine9.setText("18");
      lblMachine9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      leftPanel.add(lblMachine9);

      rightPanel.setLayout(new java.awt.GridLayout(3, 4, 5, 5));

      lblMachine18.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine18.setText("3");
      lblMachine18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine18);

      lblMachine21.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine21.setText("2");
      lblMachine21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine21);

      lblMachine22.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine22.setText("1");
      lblMachine22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine22);

      lblMachine23.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine23);

      lblMachine24.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine24.setText("10");
      lblMachine24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine24);

      lblMachine25.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine25.setText("9");
      lblMachine25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine25);

      lblMachine26.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine26.setText("8");
      lblMachine26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine26);

      lblMachine27.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine27.setText("7");
      lblMachine27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine27);

      lblMachine28.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine28.setText("17");
      lblMachine28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine28);

      lblMachine29.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine29.setText("16");
      lblMachine29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine29);

      lblMachine30.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine30.setText("15");
      lblMachine30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine30);

      lblMachine31.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine31.setText("14");
      lblMachine31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      rightPanel.add(lblMachine31);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addGap(39, 39, 39)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel lblMachine12;
   private javax.swing.JLabel lblMachine18;
   private javax.swing.JLabel lblMachine2;
   private javax.swing.JLabel lblMachine21;
   private javax.swing.JLabel lblMachine22;
   private javax.swing.JLabel lblMachine23;
   private javax.swing.JLabel lblMachine24;
   private javax.swing.JLabel lblMachine25;
   private javax.swing.JLabel lblMachine26;
   private javax.swing.JLabel lblMachine27;
   private javax.swing.JLabel lblMachine28;
   private javax.swing.JLabel lblMachine29;
   private javax.swing.JLabel lblMachine3;
   private javax.swing.JLabel lblMachine30;
   private javax.swing.JLabel lblMachine31;
   private javax.swing.JLabel lblMachine4;
   private javax.swing.JLabel lblMachine5;
   private javax.swing.JLabel lblMachine6;
   private javax.swing.JLabel lblMachine7;
   private javax.swing.JLabel lblMachine8;
   private javax.swing.JLabel lblMachine9;
   private javax.swing.JPanel leftPanel;
   private javax.swing.JPanel rightPanel;
   // End of variables declaration//GEN-END:variables
}
