/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.maps;

/**
 *
 * @author mark
 */
public class MapPanel317 extends javax.swing.JPanel {

   /**
    * Creates new form MapPanel317
    */
   public MapPanel317() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel5 = new javax.swing.JPanel();
      pnlMain = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      lblMachine10 = new javax.swing.JLabel();
      lblMachine9 = new javax.swing.JLabel();
      jPanel6 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      lblMachine2 = new javax.swing.JLabel();
      lblMachine1 = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      lblMachine8 = new javax.swing.JLabel();
      lblMachine7 = new javax.swing.JLabel();
      jPanel4 = new javax.swing.JPanel();
      lblMachine5 = new javax.swing.JLabel();
      lblMachine6 = new javax.swing.JLabel();
      jPanel7 = new javax.swing.JPanel();
      lblMachine4 = new javax.swing.JLabel();
      lblMachine3 = new javax.swing.JLabel();

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );

      pnlMain.setLayout(new java.awt.GridLayout(2, 3, 20, 20));

      jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

      lblMachine10.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine10.setText("10");
      lblMachine10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel1.add(lblMachine10);

      lblMachine9.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine9.setText("9");
      lblMachine9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel1.add(lblMachine9);

      pnlMain.add(jPanel1);

      jPanel6.setLayout(new java.awt.GridLayout(1, 2, 5, 0));
      pnlMain.add(jPanel6);

      jPanel2.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

      lblMachine2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine2.setText("2");
      lblMachine2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel2.add(lblMachine2);

      lblMachine1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine1.setText("1");
      lblMachine1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel2.add(lblMachine1);

      pnlMain.add(jPanel2);

      jPanel3.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

      lblMachine8.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine8.setText("8");
      lblMachine8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel3.add(lblMachine8);

      lblMachine7.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine7.setText("7");
      lblMachine7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel3.add(lblMachine7);

      pnlMain.add(jPanel3);

      jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

      lblMachine5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine5.setText("5");
      lblMachine5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel4.add(lblMachine5);

      lblMachine6.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine6.setText("6");
      lblMachine6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel4.add(lblMachine6);

      pnlMain.add(jPanel4);

      jPanel7.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

      lblMachine4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine4.setText("4");
      lblMachine4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel7.add(lblMachine4);

      lblMachine3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
      lblMachine3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblMachine3.setText("3");
      lblMachine3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      jPanel7.add(lblMachine3);

      pnlMain.add(jPanel7);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JPanel jPanel7;
   private javax.swing.JLabel lblMachine1;
   private javax.swing.JLabel lblMachine10;
   private javax.swing.JLabel lblMachine2;
   private javax.swing.JLabel lblMachine3;
   private javax.swing.JLabel lblMachine4;
   private javax.swing.JLabel lblMachine5;
   private javax.swing.JLabel lblMachine6;
   private javax.swing.JLabel lblMachine7;
   private javax.swing.JLabel lblMachine8;
   private javax.swing.JLabel lblMachine9;
   private javax.swing.JPanel pnlMain;
   // End of variables declaration//GEN-END:variables
}
